const ActionTypes = {
    CURRENTUSERDATA: "CURRENTUSERDATA",
    USERS: "USERS",
    SIGNUPERROR: "SIGNUPERROR",
    SIGNINERROR: "SIGNINERROR",
    SIGNINERRORSTATE: "SIGNINERRORSTATE", 
    SIGNUPERRORSTATE: "SIGNUPERRORSTATE",
    LOADING: "LOADING",
    ISLOADING: "ISLOADING"
}

export default ActionTypes;
